version = 0.1
[default.deploy.parameters]
stack_name = "co-apt-stack"
resolve_s3 = true
s3_prefix = "co-apt-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
